[project]
name = "simplerag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm>=0.23",
    "llm-gpt4all>=0.4",
    "llm-sentence-transformers>=0.3.1",
    "pymupdf>=1.25.4",
    "sentence-transformers>=4.0.1",
]
